apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-storage
  namespace: cns-test
  annotations:
     storageclass.kubernetes.io/is-default-class: "true"
provisioner: efs-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"