apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsrc
  namespace: test-ns
spec:
  replicas: 2
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
     maxSurge: 1
  minReadySeconds: 30
  selector:
   matchLabels:
    app: nodeapp
  template:
    metadata:
      name: nodeapp
      labels:
        app: nodeapp
    spec:
        containers:
         - name: nodeappcontainer
           image: nginx
           ports:
           -  containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nodejsservice
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
  - port: 8080
    targetPort: 80