apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejsrc
  namespace: test-ns
spec:
  replicas: 1
  selector:
    app: nodeapp
  template:
    metadata:
      name: nodeapp
      labels:
        app: nodeapp
    spec:
        containers:
         - name: nodeappcontainer
           image: nginx
           ports:
            -  containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nodejreplicaservice
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
  - port: 8080
    targetPort: 80